### ISSUE TITLE
Robust Finger movements

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/hmi_2015#25]
One click one move (each command should move the gripper)

clamping

Emergency and recover

**Comment by fmessmer** [comment]
The grippers mainly failed as soon as a Cartesian path (planned by MoveIt!) is being executed.
Reducing the `eef_step` parameter "solved" the problem for know.

Thus, I think the problem is not mainly related to temperature, but might be related to jerky motion and a firmware reboot...as the duration until the gripper is able to be moved again is almost always the same and the movements of compute_cartesian_path are somewhat jerky due to the hardcoded 0.2 duration per trajectory point....

Still needs further investigation!

**Comment by fmessmer** [comment]
also see https://github.com/ipa320/cob4/issues/183

**Comment by fmessmer** [comment]
Wontfix within hmi2015
